### ISSUE TITLE
[Improvement] Replacement for Default upload window when changing default explorer to Files

### ISSUE THREAD

**Issue by Jackaroo05** [files-community/files-community.github.io#62] opened 2021-03-15 16:19 UTC
![image](https://user-images.githubusercontent.com/22356378/111185679-9bbf8b00-8588-11eb-976f-c2ff38b5dd76.png)
I was thinking if possible for a way to change this into files when the default explorer is changed to files. I don't know if it is even possible, but if it is, I'd like to see it.

**Comment by yaichenbaum** [comment] 2021-03-19 03:00
Duplicate of #61.

**Closed by yaichenbaum** 2021-03-19 03:00 UTC
